### ISSUE TITLE
HTML Templates Generation

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#147]
HTML templates that contains AngularJS code are not generated properly by the Mustache engine:

**Before generation:**
```html
<tr ng-repeat="customer in customers">
  <td>{{customer.CompanyName}}</td>
  <td>{{customer.City}}</td>
  <td>{{customer.Address}}</td>
</tr>
```

**After generation:**
```html
<tr ng-repeat="customer in customers">
  <td></td>
  <td></td>
  <td></td>
</tr>
```

Possible solutions:
- Change the open/close AngluarJS tag
- Change the generation engine for such templates (e.g. Velocity)

**Comment by shturec** [comment]
option 3 (and probably most applicable here) - change the open/close tags of moustache for angular templates only: [https://mustache.github.io/mustache.5.html](https://mustache.github.io/mustache.5.html) (see section Set Delimiter)

I claim it most applicable because it will keep the generated angular code aligned with the angular developers expectations. That's on our expense of course but that's the way it should be with dev-oriented tools production.

**Comment by delchev** [comment]
Example with optional **start** and **end** parameters on source file level:
```
exports.getTemplate = function() {
	return {
		"name": "HTML",
		"description": "HTML Template",
		"sources": [{
			"location": "/template-html/index.html.template", 
			"action": "generate",
			"rename": "{{fileName}}.html",

			"start" : "[[",
			"end" : "]]"

		}],
		"parameters": []
	};
};
```
