### ISSUE TITLE
[Documentation] 404 at "REST Calls"

### ISSUE THREAD

**Issue by koppor** [eclipse/dirigible#1900]
At https://www.dirigible.io/samples/:

![image](https://user-images.githubusercontent.com/1366654/176178001-7561e891-2570-4d1b-beec-336d60901c39.png)

That leads to https://www.dirigible.io/samples/basic/rest-calls, which is 404.

Oliver Kopp &lt;<oliver.kopp@mbition.io>&gt;, on behalf of [MBition GmbH](https://mbition.io/). [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md).

**Comment by ThuF** [comment]
Hi Oliver,

Thank you for submitting this issue! It seems that there are two more pages that were also moved to new locations:
- https://www.dirigible.io/samples/basic/convert-json2xml
- https://www.dirigible.io/samples/basic/convert-xml2json

Regards,
Yordan

**Comment by ThuF** [comment]
Fixed with:
- https://github.com/dirigible-io/dirigible-io.github.io/commit/6dfa4b621d494acf22476eb2be9c48ab70008a5a
- https://github.com/dirigible-io/dirigible-io.github.io/commit/5f6ba9978513418fc9778d8ab0c5b3b839c2c438

@koppor now the links should work as expected:
- https://www.dirigible.io/samples/basic/rest-calls
- https://www.dirigible.io/samples/basic/convert-json2xml
- https://www.dirigible.io/samples/basic/convert-xml2json
