### ISSUE TITLE
Links from feature page are 404

### ISSUE THREAD

**Issue by koppor** [eclipse/dirigible#281]
1. Open http://www.dirigible.io/features.html
2. Click "Integration Flows"
3. Expected result: A web page opens

Actual result: http://www.dirigible.io/help/integration_services.html opens and GitHub shows 404.

![grafik](https://user-images.githubusercontent.com/1366654/41356881-21d34ac4-6f25-11e8-9327-6531b01aa4d7.png)

**Comment by delchev** [comment]
Hi Oliver,

Thanks a lot for reporting this issue!

It is fixed with: https://github.com/dirigible-io/dirigible-io.github.io/commit/183ee168f3ef25aeb2b01ad848199b6e3b85cc73

Just as an additional information about the Connectivity section above - we used Apache Camel in some older versions, which still not available in the most recent one. If you need Camel integration, because Flowable + Enterprise API does not cover your scenario, just let me know.

Regards,
Nedelcho
