### ISSUE TITLE
[EDM] Custom Actions for Entities to be Introduced

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#2900]
Custom actions for entities to be introduced and added in the heading sections of the Primary entities.

1. To be generated corresponding Extension Point
2. All the Custom Actions should appear next to the predefined ones or at each of the items:

<img width="568" alt="custom-actions" src="https://github.com/eclipse/dirigible/assets/6852373/2cdaa34a-9466-42ef-b681-c4e466960049">

<img width="104" alt="custom-actions-list" src="https://github.com/eclipse/dirigible/assets/6852373/c7ae3650-0800-4b24-b566-74a08301eb03">

4. Every Custom Action's Extension should provide:

* Name (e.g. 'Generate', 'Print', etc.)
* URL (the endpoint, which has to be called)
* Method (GET, POST)

5. Executing the Custom Action means calling the URL by providing the `ID` of the selected entity

**Comment by ThuF** [comment]
Custom actions can be implemented via **messageHub** integration instead of **request/response** integration.

In addition to the request/response capabilities, this approach will allow better integration and interaction with the UI (e.g. show/hide custom dialog, show alerts, etc.).

Example of such kind of integration can be found here:

## Custom Action Controller File
<img width="908" alt="custom-action-controller" src="https://github.com/eclipse/dirigible/assets/4092083/92fd0796-f7c2-410c-ae52-303029649248">

## Main Controller
<img width="940" alt="controller" src="https://github.com/eclipse/dirigible/assets/4092083/1ec1034c-47bc-4002-afcf-2e7a89785339">

## Main Page
<img width="1007" alt="page" src="https://github.com/eclipse/dirigible/assets/4092083/c1419c6c-7097-457d-945a-bbb8e24cc32f">

**Comment by ThuF** [comment]
Better approach was found:
- Generic `Custom Action` dialog is introduced _(one per project)_.
- The dialog is used as a generic container for the action view.
- The "real" action view is provided via link and it's loaded in `iframe` inside the generic dialog.

https://github.com/eclipse/dirigible/assets/4092083/36726015-0a32-4e66-a046-4136f8b1e6a2

Demo projects:
- [test-20231213075427.zip](https://github.com/eclipse/dirigible/files/13663999/test-20231213075427.zip) - contains the EDM model.
- [test-custom-actions-20231213075429.zip](https://github.com/eclipse/dirigible/files/13664000/test-custom-actions-20231213075429.zip) - contains the custom actions.

The custom action extension has to implement the following method:

```js
exports.getAction = function () {
    return {
        id: 'id',
        label: 'Label',
        type: 'page', // optional - 'page' or 'entity', by default is 'page'
        link: '/',
       order: 10 // optional
    }
}
```
