### ISSUE TITLE
[EDM] Server side validations to be introduced

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#3304]
Server side validations to be introduced to eventually stop and report for CUD like operations

**Comment by ThuF** [comment]
Error message enhancement for pattern validation:
<img width="939" alt="Screenshot 2024-02-29 at 18 41 54" src="https://github.com/eclipse/dirigible/assets/4092083/f69f27ac-9bc4-43aa-b5f2-996278b30237">

Server side validation:
<img width="1102" alt="Screenshot 2024-02-29 at 18 42 09" src="https://github.com/eclipse/dirigible/assets/4092083/54babb7f-e9eb-4598-a04b-b2a38ba660ec">

**Comment by ThuF** [comment]
## Changes

- Add server side validation via extension point (in the REST API).
- One common extension point for both `trigger` (DAO) and `validate` (REST API) events.
- The extension point was renamed from `${projectName}/${perspectiveName}/${name}` to `${projectName}-${perspectiveName}-${name}` as the `/` symbol is invalid inside the Extensions editor.
- Enhanced validation messages both in the frontend and the backend.
- Add validations for `required` properties and for `data length` of string properties.
- Removes input rules (validation patterns) from the `Filter Dialogs`.

## Example

**validation/Student.ts**
```ts
import { StudentEntity } from "../gen/dao/entities/StudentRepository";

export const validate = (entity: StudentEntity) => {
    if (entity.Name && entity.Name.length > 13) {
        throw new Error('Validation failed because Name is longer than 13 symbols');
    }
}
```

**validation/Student.extension**
```json
{
    "module": "demo/validation/Student",
    "extensionPoint": "demo-entities-Student",
    "description": "Student Extension"
}
```

## Note

The value of the `module` in the extension definition is set to:

```json
"module": "demo/validation/Student"
```

 instead of 

```json
"module": "demo/validation/Student.ts"
```

Due to unknown reasons at the moment the `*.ts` extension is not loaded properly when there are `top-level awaits` in the code:

```ts
const validationModules = await Extensions.loadExtensionModules("demo-entities-Student", ["validate"]);
```

So either the module should be specified without providing the extension, or by setting `*.js` extension (`"module": "demo/validation/Student.js"`)
