### ISSUE TITLE
UI Bug: 'Push' Button Stays Enabled After Clicking 'Commit and Push'

### ISSUE THREAD

**Issue by alt-plus-f4** [eclipse/dirigible#4077]
**Description:**
When using the GitHub tab in Eclipse Dirigible, there is an issue with the button states after attempting to commit and push changes. Specifically, when the 'Commit and Push' button is clicked, both the 'Commit' and 'Commit and Push' buttons get disabled, but the 'Push' button remains enabled.

**Steps to Reproduce:**
Open the GitHub tab in Eclipse Dirigible.
Make some changes to a file in the project.
Click the 'Commit and Push' button.

**Expected Behavior:**
All buttons related to committing and pushing (i.e., 'Commit', 'Commit and Push', and 'Push') should be disabled after initiating the commit and push operation to prevent further actions after completion.

**Actual Behavior:**
The 'Commit' and 'Commit and Push' buttons get disabled, but the 'Push' button remains enabled.

**Screenshots:**
How it is:
<img width="267" alt="image" src="https://github.com/eclipse/dirigible/assets/79216061/d43615e5-810e-4fad-8cb0-7e428d549c72">
How it should be:
<img width="251" alt="image2" src="https://github.com/eclipse/dirigible/assets/79216061/ed1b5ea8-f123-48d5-a579-b5c96c9ca6de">

**Environment:**
    Eclipse Dirigible Version: (latest - 10.6.1)
    OS: (Windows 10)

**Comment by StanZGenchev** [comment]
This is not a bug, it's the intended behavior. This is how git works and the Git perspective just mimics it.

The "Commit" and "Commit & Push" buttons have a disabled state because you do not always have something to commit. However, you can **always** push.

Let's say that you commit some changes but you can't/don't push the commit (there is no internet connection at the moment or you are not sure if you will be making any additional changes).
Then after some time passes, you decide that it's time to push your changes.
With the current behavior, you can just click "Push" and it will be done.
With the proposed behavior, you will have to make some changes and then commit & push them. Not only will this add unnecessary commits, it will also make the separate "Push" button redundant since you will not be able to push if you do not have changes to commit.

**Comment by alt-plus-f4** [comment]
On refresh or resetting the cache (theme) the push button gets disabled. If it was expected behavior it should stay enabled.
