### ISSUE TITLE
Debugger not working on try out dirigible.io

### ISSUE THREAD

**Issue by Demonium** [eclipse/dirigible#506]
**Describe the bug**
Debugger not working on try out dirigible.io

**To Reproduce**
1. Go to 'workspace'
2. create new folder
3. create new javascript service
4. go to debugger
5. put debug point on any line
6. start debugger
7. refresh preview

**Expected behavior**
debugger started
**Screenshots**
**Additional context**
on dirigible.io try out after opening the console we see a javascript error see below
VM211:37 Error: Failed to construct 'WebSocket': The URL 'wss' is invalid.
    at controller.js:203
    at angular.js:14745
    at n.$eval (angular.js:15989)
    at n.$digest (angular.js:15800)
    at n.$apply (angular.js:16097)
    at h (angular.js:10546)
    at K (angular.js:10744)
    at XMLHttpRequest.z.onload (angular.js:10685)
window.console.error @ VM211:37
2/services/v4/ide/debug/rhino/session/stepInto:1 Failed to load resource: the server responded with a status of 500 ()

**Comment by delchev** [comment]
Hi Jonathan,
Due to a special authentication mechanism for Trial, the debugger didn't work correctly.
It should be fixed now with:
https://github.com/eclipse/dirigible/commit/7b38b9a2abdb820579946f678cd09b3c29f581cc
and
https://github.com/eclipse/dirigible/commit/cdfd91b677b8e3c4a71df5e1a4b95f294c57e737
Please, confirm.
(the trial cluster is with a little resources, so it still might be slow...)
Regards,
Nedelcho

**Comment by Demonium** [comment]
Seems to be ok now
