### ISSUE TITLE
Cannot load Dirigible from the manager application of tomcat

### ISSUE THREAD

**Issue by malkoto1** [eclipse/dirigible#603]
Case: I am trying to deploy the dirigible the most basic way: I just enter the manager app of tomcat and go to "**WAR file to deploy**" section and deploy it through there. 

After clicking the "**Deploy**" button the result is as follows:
![image](https://user-images.githubusercontent.com/1436515/93568777-533c6180-f999-11ea-9b26-59dde6be46c1.png)

After that, I can see the "**ROOT**" folder unpacked under _webapps_ folder but I cannot see it in the "**Applications**" section of the manager app.

**Tomcat is version 9.**

**Comment by g051051** [comment]
This is due to a setting in Tomcat.  The manager app has a default file size limit of 50Mb, which is smaller than the war files for Dirigible.  I changed the settings to increase the limit from 50Mb to 150Mb (using info from [this StackOverflow post](https://stackoverflow.com/questions/2947683/httprequest-maximum-allowable-size-in-tomcat)) and was able to deploy the desktop-all war file successfully.

**Comment by delchev** [comment]
A section about Manager App approach for deployment on Apache Tomcat is added in the help page:
https://www.dirigible.io/help/setup_tomcat.html
