### ISSUE TITLE
App preview in new window is not updated

### ISSUE THREAD

**Issue by fifoosid** [eclipse/dirigible#644]
**Describe the bug**

When using dirigible on Kyma, i happened to observe a strange behaviour when testing the app in new tab(not in the preview tab that is available).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a project in dirigible hosted on Kyma
2. Copy the URL from the preview panel and open it in a new tab
3. Make any changes to the file(in my case HTML file)
4. Save the file
5. Refresh the preview in the other tab
6. You can notice that the changes are not applied.
7. Now if you save the file again(even with no new changes) and then refresh the other tab, you will be able to see your changes

If you need any help reproducing the issue, you can contact me

**Comment by ThuF** [comment]
I've been able to reproduce the issue, but only with `*.html` files.

Findings:
1. The HTTP requests are executed as expected.
2. The content in the **user's workspace** is as expected
    - `/usr/local/tomcat/target/dirigible/repository/root/users/<user-id>/workspace/demo/file.html`
3. The content in the **Registry** is not updated, which is actually causing the issue:
    - `/usr/local/tomcat/target/dirigible/repository/root/registry/public/demo/file.html`

So far the issue was reproduced in the Kyma environment, more tests on the other environments to be done.

**Comment by ThuF** [comment]
Closing this issue as outdated, @fifoosid please reopen it if you can still reproduce it.
