### ISSUE TITLE
PostgreSQL and Dirigible incompatibility issue  

### ISSUE THREAD

**Issue by ujval-kalal** [eclipse/dirigible#649]
**Describe the bug**
By default PostgreSQL understands the setObject() method as setVarchar(), So it tries to convert the number to a char

**To Reproduce**
Posting data to PostgreSQL db using Api Post call

**Expected behavior**
I should return integer value 

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/72190161/99666395-fb050700-2a90-11eb-889c-55c8d8fb165b.png)

**Desktop (please complete the following information):**
 - OS: windows 10 pro
 - Browser: Chrome
 - Version: 86.0.4240.198 

**Additional information**

Above issue was resolved by using explicitly type casting

eg: 
query.execute("SELECT \"STUDYINVESTIGATORMAPID\" FROM \"PHARM_STUDY_INVESTIGATOR_MAP\" WHERE \"STUDYEXECUTIONID\" = ? AND \"INVESTIGATORID\" = ?", [{type: "INTEGER", value: studyExecutionId}, {type: "INTEGER", value: investigatorId}]);

**Comment by ThuF** [comment]
The issue is part of the `db/query` API and more specifically it is located in the [DatabaseFacade]( https://github.com/eclipse/dirigible/blob/master/api/api-facade/api-database/src/main/java/org/eclipse/dirigible/api/v3/db/DatabaseFacade.java#L401-L402). As @ujval-kalal  pointed it appears that in the PostgreSQL driver, the default behaviour of the `setObject()` method results into `setString()` with explicit `varchar` data type conversion.
