### ISSUE TITLE
Broken URLs after the migration

### ISSUE THREAD

**Issue by d12xman** [eclipse/dirigible#690]
[dirigible.xlsx](https://github.com/eclipse/dirigible/files/5862445/dirigible.xlsx)
Hello, 
I am attaching a file with the old URLs that are not redirected to the new. 
Please redirected the 404s or this will be an issue for the SEO.

**Comment by ThuF** [comment]
Fixed with:
- https://github.com/dirigible-io/dirigible-io.github.io/commit/354d99edb99d1453f24eb8a867f7b27a0805f775
- https://github.com/dirigible-io/dirigible-io.github.io/commit/21d422b894d631ab99e769c3a2e7874b4516012f
- and few previous commits

@d12xman could you please re-test the pages, from SEO point of view?
