### ISSUE TITLE
[UI Improvement] Unify icons of perspectives in the sidebar and window menu entries

### ISSUE THREAD

**Issue by slavipande** [eclipse/dirigible#703]
**Description**
The list of perspectives in the Window menu has a different order than the icons of the perspectives in the sidebar. 

**To Reproduce**
1. Go to 'Workbench' perspective
2. Click on 'Window > Open Perspective'
3. See the list of perspectives
4. Compare with the perspectives in the sidebar.

**Expected behavior**
The list of perspectives and the perspectives in the sidebar are unified.

**Screenshot**
<img width="399" alt="2021-01-22_18-33-11" src="https://user-images.githubusercontent.com/46915717/106451609-7b7fb500-648f-11eb-91eb-add3b38f64c0.png">

**Desktop:**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 88.0.705.56 (Official build) (64-bit)

**Comment by ThuF** [comment]
Font Awesome 5 icons to be considered as well: https://fontawesome.com/icons?d=gallery&m=free

> _**[Font Awesome CDN](https://cdnjs.com/libraries/font-awesome):** https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css_

**Comment by ThuF** [comment]
Alphanumeric sorting of the perspectives is applied as part of: https://github.com/eclipse/dirigible/issues/740

With that we can consider the issue fixed, as from usability point of view, it is more important to have a sorted list instead of `1:1` matching between the list items and the sidebar icons.
